spring:
  config:
    activate:
      on-profile: staging

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.skillseed: INFO
