spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/skillseed
    username: postgresqladmin
    password: postgresqladmin

  data:
    redis:
      url: redis://:redisadmin@localhost:6379

logging:
  level:
    com.skillseed: DEBUG
